# Generated by Django 4.0.2 on 2023-05-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='demo.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(blank=True, null=True, to='demo.Character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='demo.Book'),
        ),
    ]
