# Generated by Django 4.0.2 on 2023-05-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_book_author_alter_book_characters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='books',
        ),
    ]
