# Generated by Django 4.0.2 on 2023-05-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_remove_character_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='demo.Character'),
        ),
    ]
